name: Deploy to Vercel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to Vercel
        run: npx vercel --prod --token=${{ secrets.VERCEL_TOKEN }} --yes
        env:
          VERCEL_ORG_ID: team_KUwCmidMcphdigr3fT1hVz3n
          VERCEL_PROJECT_ID: prj_2u2YBCEvQ8DUe5Z059arPJkIRoD8
